let popup = document.createElement("div");
    popup.style.position = "fixed";
    popup.style.top = "10px";
    popup.style.left = "50%";
    popup.style.transform = "translateX(-50%)";
    popup.style.backgroundColor = "rgba(255, 255, 255, 0.2)";
    popup.style.color = "white";
    popup.style.padding = "8px 15px";
    popup.style.borderRadius = "5px";
    popup.style.boxShadow = "0px 2px 10px rgba(0, 0, 0, 0.8)";
    popup.style.fontSize = "16px";
    popup.style.whiteSpace = "nowrap";
    popup.style.zIndex = "1000";
	popup.id = "popup-message";
	popup.style.textAlign = "center";
	let text = document.createElement("p");
	text.id = "popup-text";
	text.textContent = "Are you sure you want to exit?";
	text.style.fontsize = "1vw";
	popup.appendChild(text);
	let text2 = document.createElement("p");
	text2.id = "popup-text";
	text2.textContent = "Your current game progress will be lost";
	text2.style.fontSize = "0.6vw"
	popup.appendChild(text2);
	let buttonContainer = document.createElement("div");
	buttonContainer.style.marginTop = "15px";
	buttonContainer.style.marginBottom = "5px";
	buttonContainer.id = "popup-buttons";
	buttonContainer.style.display = "flex";
	buttonContainer.style.flexDirection = "row";
	buttonContainer.style.justifyContent = "space-around"
	let continueBtn = document.createElement("button");
	continueBtn.className = "btn btn-primary btn-sm";
	continueBtn.textContent = "STAY";
	continueBtn.fontSize = "1vw";
	buttonContainer.appendChild(continueBtn);
	let exitBtn = document.createElement("button");
	exitBtn.className = "btn btn-danger btn-sm";
	exitBtn.textContent = "EXIT";
	exitBtn.fontSize = "1vw";
	buttonContainer.appendChild(exitBtn);
	popup.appendChild(buttonContainer);
	popup.className = "position-fixed top-0 start-50 translate-middle-x bg-dark text-white text-center p-3 rounded shadow-lg";
	popup.style.fontSize = "1vw";
	document.body.appendChild(popup);
